# INTEL CONFIDENTIAL
# Copyright (2019) Intel Corporation.
#
# The source code contained or described herein and all documents related to the source code ("Material")
# are owned by Intel Corporation or its suppliers or licensors. Title to the Material remains with
# Intel Corporation or its suppliers and licensors. The Material may contain trade secrets and proprietary
# and confidential information of Intel Corporation and its suppliers and licensors, and is protected by
# worldwide copyright and trade secret laws and treaty provisions. No part of the Material may be used,
# copied, reproduced, modified, published, uploaded, posted, transmitted, distributed, or disclosed in
# any way without Intel/'s prior express written permission.
# No license under any patent, copyright, trade secret or other intellectual property right is granted
# to or conferred upon you by disclosure or delivery of the Materials, either expressly, by implication,
# inducement, estoppel or otherwise. Any license under such intellectual property rights must be express
# and approved by Intel in writing.
# Unless otherwise agreed by Intel in writing, you may not remove or alter this notice or any other
# notice embedded in Materials by Intel or Intel's suppliers or licensors in any way.

FROM golang:1.12-alpine as gobuilder

ENV GO111MODULE=on

RUN echo http://nl.alpinelinux.org/alpine/v3.6/main > /etc/apk/repositories; \
    echo http://nl.alpinelinux.org/alpine/v3.6/community >> /etc/apk/repositories

RUN apk update && apk add bash git

# Authentication needed to pull git modules from github.impcloud.net
RUN git config --global credential.helper store
ARG GIT_TOKEN
RUN set +x && echo "https://$GIT_TOKEN:x-oauth-basic@github.impcloud.net" > ~/.git-credentials

WORKDIR $GOPATH/src/github.impcloud.net/RSP-Inventory-Suite/mqtt-device-service

# Download go modules first so they can be cached for faster subsequent builds
COPY go.mod go.mod
RUN go mod download

COPY . .

RUN ./build.sh

FROM scratch

COPY /cmd /
COPY --from=gobuilder /go/src/github.impcloud.net/RSP-Inventory-Suite/mqtt-device-service/mqtt-device-service /

ENV APP_PORT=49982
EXPOSE $APP_PORT

ENTRYPOINT ["/mqtt-device-service"]
CMD ["--profile=docker","--confdir=/res"]
