[Incoming]
Protocol = "tcp"
Host = ""
Port = 1883
Username = "admin"
Password = "public"
Qos = 0
KeepAlive = 3600
MqttClientId = "IncomingDataSubscriber"
Topics = ["DataTopic"]

[Response]
Protocol = "tcp"
Host = ""
Port = 1883
Username = "admin"
Password = "public"
Qos = 0
KeepAlive = 3600
MqttClientId = "CommandResponseSubscriber"
Topics = ["ResponseTopic"]