[Service]
Host = "localhost"
Port = 49982
ConnectRetries = 3
Labels = []
OpenMsg = "mqtt device service started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "localhost"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "./device-mqtt.log"

[Writable]
LogLevel = "DEBUG"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "localhost"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

# Pre-define Devices
[[DeviceList]]
  Name = "rrs-gateway"
  Profile = "Gateway.Device.MQTT.Profile"
  Description = "Gateway Device MQTT Broker Connection"
  Labels = [ "MQTT", "Gateway", "RFID"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "mosquitto-server"
       Port = "1883"
       User = ""
       Password = ""
       ClientId = "CommandPublisher"
       Topic = "rfid/gw/command"
#  [[DeviceList.AutoEvents]]
#    Frequency = "20s"
#    OnChange = false
#    Resource = "testrandfloat32"

# Driver configs
[Driver]
IncomingSchema = "tcp"
IncomingHost = "mosquitto-server"
IncomingPort = "1883"
IncomingUser = ""
IncomingPassword = ""
IncomingQos = "1"
IncomingKeepAlive = "3600"
IncomingClientId = "IncomingDataSubscriber"
IncomingTopic = "rfid/gw/events"
ResponseSchema = "tcp"
ResponseHost = "mosquitto-server"
ResponsePort = "1883"
ResponseUser = ""
ResponsePassword = ""
ResponseQos = "1"
ResponseKeepAlive = "3600"
ResponseClientId = "CommandResponseSubscriber"
ResponseTopic = "rfid/gw/response"
