# Defines how EdgeX communicates with the DeviceService

# For EdgeX to send messages to the DeviceService
[Incoming]
Protocol = "tls"
Host = "mosquitto-server"
Port = 9883
Qos = 1
KeepAlive = 3600
MqttClientId = "IncomingDataSubscriber"
Topics = [
    "rfid/gw/events",
    "rfid/gw/alerts",
    "rfid/gw/heartbeat"
]


# For EdgeX to receive messages from the DeviceService
[Response]
Protocol = "tls"
Host = "mosquitto-server"
Port = 9883
Qos = 1
KeepAlive = 3600
MqttClientId = "CommandResponseSubscriber"
Topics = ["ResponseTopic"]
