[Incoming]
Protocol = "tcp"
Host = "mosquitto-server"
Port = 1883
Qos = 1
KeepAlive = 3600
MqttClientId = "IncomingDataSubscriber"
Topics = [
    "rfid/gw/events",
    "rfid/gw/alerts",
    "rfid/gw/heartbeat"
]
MetaDataPort = 48081

[Command]
Protocol = "tcp"
Host = "mosquitto-server"
Port = 1883
Qos = 1
KeepAlive = 3600
MqttClientId = "CommandPublisher"
Topics = ["rfid/gw/command"]

[Response]
Protocol = "tcp"
Host = "mosquitto-server"
Port = 1883
Qos = 1
KeepAlive = 3600
MqttClientId = "CommandResponseSubscriber"
Topics = ["rfid/gw/response"]