# used to configured the Service & Addressable in the MetaData service

[Service]
Host = "ajsaites-desk.amr.corp.intel.com"
Port = 49982
ConnectRetries = 3
Labels = []
OpenMsg = "gateway device service started"
ReadMaxLimit = 256
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "192.168.99.101"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "192.168.99.101"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "192.168.99.101"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "192.168.99.101"
  Port = 48061

[Device]
  DataTransform = true
  ProfilesDir = "./res"
  InitCmd = ""
  InitCmdArgs = ""
  # probably will need to increase these significantly
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""

[Logging]
EnableRemote = true
File = "./device-gateway-mqtt.log"
Level = "DEBUG"

# Pre-define Devices
[[DeviceList]]
  Name = "rrs-gateway"
  Profile = "Gateway.Device.MQTT.Profile"
  Description = "Gateway Device MQTT Broker Connection"
  Labels = [ "MQTT", "Gateway", "RFID"]
  [DeviceList.Addressable]
    Name = "Gateway address"
    Protocol = "TCP"
    Address = "192.168.99.100"
    Port = 9883
    Publisher = "CommandPublisher"
    User = "saf"
    Password = "xA18HiKy218Lm28YklwIBHaALFgYrbnNa1XIHb3ntyTib9Stm4PyC74nh7Ic1vz"
    Topic = "rfid/edgex/command"

