# used to configured the Service & Addressable in the MetaData service

[Service]
Host = "gateway-device-service"
Port = 49982
ConnectRetries = 3
Labels = []
OpenMsg = "gateway device service started"
ReadMaxLimit = 256
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  ProfilesDir = "./res"
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""

[Logging]
EnableRemote = true
File = "./device-gateway-mqtt.log"
Level = "DEBUG"

# Defines how EdgeX communicates with an individual device
[[DeviceList]]
  Name = "rrs-gateway"
  Profile = "Gateway.Device.MQTT.Profile"
  Description = "Gateway Device MQTT Broker Connection"
  Labels = [ "MQTT", "Gateway", "RFID"]
  [DeviceList.Addressable]
    Name = "Gateway address"
    Protocol = "TCP"
    Address = "rrs-gateway"

