[Service]
Host = "mqtt-device-service"
Port = 49982
ConnectRetries = 3
Labels = []
OpenMsg = "mqtt-device-service started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "./mqtt-device-service.log"

[Writable]
LogLevel = "DEBUG"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

# Pre-define Devices
[[DeviceList]]
  Name = "rsp-controller"
  Profile = "RSP-controller.Device.MQTT.Profile"
  Description = "RSP-controller Device MQTT Broker Connection"
  Labels = [ "MQTT", "RSP-controller", "RFID"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Scheme = "tcp"
       Host = "mosquitto-server"
       Port = "1883"
       User = ""
       Password = ""
       ClientId = "CommandPublisher"
       Topics = "rfid/controller/command"

# Driver configs
[Driver]
DeviceName = "rsp-controller"

# topic and message to publish to mqtt when the client is connected
OnConnectPublishTopic = "rfid/controller/command"
OnConnectPublishClientId = "CommandPublisher"

# {{uuid}} will be replaced at runtime with a generated uuid value
OnConnectPublishMessage = """\
{\
  "jsonrpc":"2.0",\
  "method":"subscribe",\
  "id":"{{uuid}}",\
  "params":[\
    "sensor_config_notification",\
    "sensor_connection_state_notification"\
  ]\
}"""

IncomingScheme = "tcp"
IncomingHost = "mosquitto-server"
IncomingPort = "1883"
IncomingUser = ""
IncomingPassword = ""
IncomingQos = "1"
IncomingKeepAlive = "3600"
IncomingClientId = "IncomingDataSubscriber"
#IncomingTopics = "rfid/controller/events,rfid/controller/alerts,rfid/controller/heartbeat,rfid/controller/notification,rfid/rsp/data/+,rfid/rsp/rsp_status/+"
IncomingTopics = "rfid/rsp/rsp_status/+"

ResponseScheme = "tcp"
ResponseHost = "mosquitto-server"
ResponsePort = "1883"
ResponseUser = ""
ResponsePassword = ""
ResponseQos = "1"
ResponseKeepAlive = "3600"
ResponseClientId = "CommandResponseSubscriber"
ResponseTopics = "rfid/controller/response"
